CREATE TABLE IF NOT EXISTS app.persona (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id INT NOT NULL,
    nombres VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    documento VARCHAR(50),
    telefono VARCHAR(50),
    email VARCHAR(254),
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_persona_organizacion
        FOREIGN KEY (organizacion_id)
        REFERENCES app.organizacion (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);