CREATE TABLE IF NOT EXISTS app.usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id INT NOT NULL,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_usuario_persona
        UNIQUE (persona_id),

    CONSTRAINT uq_usuario_username
        UNIQUE (username),

    CONSTRAINT fk_usuario_persona
        FOREIGN KEY (persona_id)
        REFERENCES app.persona (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);