CREATE TABLE IF NOT EXISTS app.reunion (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizacion_id INT NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(1000),
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME,
    lugar VARCHAR(250),
    estado VARCHAR(50) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reunion_organizacion
        FOREIGN KEY (organizacion_id)
        REFERENCES app.organizacion (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);