CREATE TABLE IF NOT EXISTS app.asistencia (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reunion_id INT NOT NULL,
    persona_id INT NOT NULL,
    codigo VARCHAR(100),
    fecha_hora_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_hora_salida TIMESTAMPTZ,
    estado VARCHAR(50) NOT NULL,

    CONSTRAINT fk_asistencia_reunion
        FOREIGN KEY (reunion_id)
        REFERENCES app.reunion (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT fk_asistencia_persona
        FOREIGN KEY (persona_id)
        REFERENCES app.persona (id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,

    CONSTRAINT uq_asistencia_reunion_persona
        UNIQUE (reunion_id, persona_id)
);