CREATE TABLE IF NOT EXISTS app.auditoria (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INT,
    accion VARCHAR(100) NOT NULL,
    entidad VARCHAR(100) NOT NULL,
    entidad_id INT,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    detalle VARCHAR(2000),

    CONSTRAINT fk_auditoria_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES app.usuario (id)
        ON UPDATE RESTRICT
        ON DELETE SET NULL
);